// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfTGVCiaHYIbHAyV2nUc7OSmnb8n7LYlo',
    appId: '1:133593788186:web:d9753c612fdbec7ad606a3',
    messagingSenderId: '133593788186',
    projectId: 'cafeboss-88282',
    authDomain: 'cafeboss-88282.firebaseapp.com',
    storageBucket: 'cafeboss-88282.firebasestorage.app',
    measurementId: 'G-8R1756W65L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAePN7B_e04WLv2u-NvBj7VuEj9biUVQsA',
    appId: '1:133593788186:android:03f151cd8abab464d606a3',
    messagingSenderId: '133593788186',
    projectId: 'cafeboss-88282',
    storageBucket: 'cafeboss-88282.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaboZZkePX_fweyxLbuwzeIn066vro8A',
    appId: '1:133593788186:ios:4bd1dcfd2bc26a4ad606a3',
    messagingSenderId: '133593788186',
    projectId: 'cafeboss-88282',
    storageBucket: 'cafeboss-88282.firebasestorage.app',
    iosBundleId: 'com.example.cafeboss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmaboZZkePX_fweyxLbuwzeIn066vro8A',
    appId: '1:133593788186:ios:4bd1dcfd2bc26a4ad606a3',
    messagingSenderId: '133593788186',
    projectId: 'cafeboss-88282',
    storageBucket: 'cafeboss-88282.firebasestorage.app',
    iosBundleId: 'com.example.cafeboss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfTGVCiaHYIbHAyV2nUc7OSmnb8n7LYlo',
    appId: '1:133593788186:web:2b9c5d48e3ad1bf0d606a3',
    messagingSenderId: '133593788186',
    projectId: 'cafeboss-88282',
    authDomain: 'cafeboss-88282.firebaseapp.com',
    storageBucket: 'cafeboss-88282.firebasestorage.app',
    measurementId: 'G-MZ0DL7BHE6',
  );
}
